In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame([(1,2,3),(4,5,6),(7,8,9)], columns=['A','B','C'], index=['X', 'Y','Z'])

In [ ]:
df.head()

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [ ]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [ ]:
df.shape

(3, 3)

In [13]:
df.size

9

In [15]:
df = pd.read_csv('/content/athlete_events.csv')

In [16]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [18]:
df.sample(10)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
171105,85988,Holger Louis Nielsen,M,29.0,NaN,NaN,Denmark,DEN,1896 Summer,1896,Summer,Athina,Shooting,"Shooting Men's Free Pistol, 30 metres",Silver
124614,62931,Pawe Jzef Korzeniowski,M,19.0,192.0,82.0,Poland,POL,2004 Summer,2004,Summer,Athina,Swimming,Swimming Men's 200 metres Butterfly,NaN
51876,26664,Lenika De Simone Blanco,F,19.0,152.0,46.0,Spain,ESP,2008 Summer,2008,Summer,Beijing,Gymnastics,Gymnastics Women's Balance Beam,NaN
82628,41975,Joseph Michael Gostigian,M,29.0,178.0,73.0,United States,USA,1992 Summer,1992,Summer,Barcelona,Modern Pentathlon,Modern Pentathlon Men's Team,NaN
115608,58574,Frederick Septimus Kelly,M,26.0,NaN,77.0,Leander Club-1,GBR,1908 Summer,1908,Summer,London,Rowing,Rowing Men's Coxed Eights,Gold
97686,49445,Poul Holm,M,19.0,NaN,NaN,Denmark,DEN,1908 Summer,1908,Summer,London,Swimming,Swimming Men's 100 metres Freestyle,NaN
196141,98476,Soundarajan Arokia Rajiv,M,25.0,175.0,65.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 4 x 400 metres Relay,NaN
214304,107593,"Edeltraud ""Traudl"" Schubert",F,18.0,162.0,52.0,West Germany,FRG,1976 Summer,1976,Summer,Montreal,Gymnastics,Gymnastics Women's Balance Beam,NaN
12250,6658,Ren Badell Pollar,M,24.0,175.0,76.0,Cuba,CUB,1972 Summer,1972,Summer,Munich,Gymnastics,Gymnastics Men's Floor Exercise,NaN
176426,88711,Ivn Jos Olivares Alvrez,M,30.0,195.0,85.0,Venezuela,VEN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN

In [24]:
df.loc[4,"Age"]

21.0

In [25]:
df.sort_values(by='Age', ascending=False)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
257054,128719,John Quincy Adams Ward,M,97.0,NaN,NaN,United States,USA,1928 Summer,1928,Summer,Amsterdam,Art Competitions,"Art Competitions Mixed Sculpturing, Statues",NaN
98118,49663,Winslow Homer,M,96.0,NaN,NaN,United States,USA,1932 Summer,1932,Summer,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN
60863,31173,Thomas Cowperthwait Eakins,M,88.0,NaN,NaN,United States,USA,1932 Summer,1932,Summer,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN
60861,31173,Thomas Cowperthwait Eakins,M,88.0,NaN,NaN,United States,USA,1932 Summer,1932,Summer,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN
60862,31173,Thomas Cowperthwait Eakins,M,88.0,NaN,NaN,United States,USA,1932 Summer,1932,Summer,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270679,135368,Antonio A. Zucchi,M,NaN,NaN,NaN,Argentina,ARG,1948 Summer,1948,Summer,London,Hockey,Hockey Men's Hockey,NaN
270774,135416,Star Zulu,M,NaN,NaN,NaN,Zambia,ZAM,1984 Summer,1984,Summer,Los Angeles,Boxing,Boxing Men's Bantamweight,NaN
270793,135426,Max Zumstein,M,NaN,NaN,NaN,Switzerland,SUI,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,NaN
270804,135434,Edmundo Ziga Erraz,M,NaN,180.0,95.0,Chile,CHI,1948 Summer,1948,Summer,London,Athletics,Athletics Men's Hammer Throw,NaN
270805,135435,Faelo Ziga,M,NaN,NaN,NaN,Chile,CHI,1928 Summer,1928,Summer,Amsterdam,Swimming,Swimming Men's 100 metres Freestyle,NaN

In [ ]:
for index, row in df.iterrows():
  print(index, row['Age'])

In [31]:
df.loc[df["Height"] > 215, ["Name","Height"]]

                                                     Name  Height
14132                                         Stanko Bara   217.0
17669                                      Gunther Behnke   221.0
22743                                            Uwe Blab   218.0
22744                                            Uwe Blab   218.0
32376                                Tommy Loren Burleson   223.0
34307                              Andrew "Andy" Campbell   218.0
34308                              Andrew "Andy" Campbell   218.0
38381                              Tyson Cleotis Chandler   216.0
47982                                 Paulo Csar da Silva   217.0
59371                              Roberto Dueas Hernndez   221.0
59372                              Roberto Dueas Hernndez   221.0
80447                                 Andreas Glyniadakis   216.0
87972                                    Hamed E. Haddadi   218.0
90309                                         Lars Hansen   216.0
99965                                         Hu Zhangbao   216.0
115016                        Aleksey Valeryevich Kazakov   217.0
115017                        Aleksey Valeryevich Kazakov   217.0
115018                        Aleksey Valeryevich Kazakov   217.0
125769                         Serhiy Ivanovych Kovalenko   216.0
125770                         Serhiy Ivanovych Kovalenko   216.0
127690                                          Jnis Krmi   218.0
127691                                          Jnis Krmi   218.0
127692                                          Jnis Krmi   218.0
138228                                           Li Muhao   218.0
141983                         Lucien James "Luc" Longley   220.0
141984                         Lucien James "Luc" Longley   220.0
141985                         Lucien James "Luc" Longley   220.0
156025                                     Salah Al-Mejri   216.0
164743                           Timofey Pavlovich Mozgov   216.0
166544                     Dmitry Aleksandrovich Musersky   219.0
177224                           Shaquille Rashuan O'Neal   216.0
181241                  Viktor Aleksandrovich Pankrashkin   220.0
183420  Paulo "Paulinho Villas Boas" Villas de Almeida...   217.0
183421  Paulo "Paulinho Villas Boas" Villas de Almeida...   217.0
196667                           Peter John Ramos Fuentes   219.0
201955                             David Maurice Robinson   216.0
201956                             David Maurice Robinson   216.0
201957                             David Maurice Robinson   216.0
207373                              Arvydas Romas Sabonis   223.0
207374                              Arvydas Romas Sabonis   223.0
207375                              Arvydas Romas Sabonis   223.0
240656                      Volodymyr Petrovych Tkachenko   220.0
240657                      Volodymyr Petrovych Tkachenko   220.0
254915                           Stojan "Stojko" Vrankovi   217.0
254916                           Stojan "Stojko" Vrankovi   217.0
254917                           Stojan "Stojko" Vrankovi   217.0
258453                             Frdric Jean Santo Weis   218.0
265040                                           Yao Ming   226.0
265041                                           Yao Ming   226.0
265042                                           Yao Ming   226.0
269053                                       Zhang Zhaoxu   221.0
269409                                            Zhou Qi   217.0
270740                                 Eurelijus ukauskas   218.0
270741                                 Eurelijus ukauskas   218.0
270742                                 Eurelijus ukauskas   218.0

In [33]:
df[(df["Height"] > 215) & (df['City']=='London')]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
38381,19736,Tyson Cleotis Chandler,M,29.0,216.0,107.0,United States,USA,2012 Summer,2012,Summer,London,Basketball,Basketball Men's Basketball,Gold
156025,78340,Salah Al-Mejri,M,26.0,216.0,110.0,Tunisia,TUN,2012 Summer,2012,Summer,London,Basketball,Basketball Men's Basketball,NaN
164743,82731,Timofey Pavlovich Mozgov,M,26.0,216.0,113.0,Russia,RUS,2012 Summer,2012,Summer,London,Basketball,Basketball Men's Basketball,Bronze
166544,83657,Dmitry Aleksandrovich Musersky,M,23.0,219.0,104.0,Russia,RUS,2012 Summer,2012,Summer,London,Volleyball,Volleyball Men's Volleyball,Gold
269053,134621,Zhang Zhaoxu,M,24.0,221.0,110.0,China,CHN,2012 Summer,2012,Summer,London,Basketball,Basketball Men's Basketball,NaN

In [37]:
df[df['Name'].str.contains("Timofey | Dmitry", case=False)]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
50033,25758,Sergey Dmitryevich Davydov,M,22.0,159.0,56.0,Belarus,BLR,2002 Winter,2002,Winter,Salt Lake City,Figure Skating,Figure Skating Men's Singles,NaN
50034,25758,Sergey Dmitryevich Davydov,M,26.0,159.0,56.0,Belarus,BLR,2006 Winter,2006,Winter,Torino,Figure Skating,Figure Skating Men's Singles,NaN
54601,28005,Timofey Aleksandrovich Deynichenko,M,25.0,186.0,98.0,Belarus,BLR,2012 Summer,2012,Summer,London,Wrestling,"Wrestling Men's Heavyweight, Greco-Roman",NaN
54602,28005,Timofey Aleksandrovich Deynichenko,M,29.0,186.0,98.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Wrestling,"Wrestling Men's Heavyweight, Greco-Roman",NaN
56432,28913,Sergey Dmitryaychev,M,25.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Double Sculls,NaN
82263,41781,Timofey Dmitriyevich Gordeychik,M,26.0,171.0,63.0,Belarus,BLR,2012 Summer,2012,Summer,London,Diving,Diving Men's Platform,NaN
113490,57497,Olga Dmitryievna Karasyova (Kharlova-),F,19.0,164.0,55.0,Soviet Union,URS,1968 Summer,1968,Summer,Mexico City,Gymnastics,Gymnastics Women's Individual All-Around,NaN
113491,57497,Olga Dmitryievna Karasyova (Kharlova-),F,19.0,164.0,55.0,Soviet Union,URS,1968 Summer,1968,Summer,Mexico City,Gymnastics,Gymnastics Women's Team All-Around,Gold
113492,57497,Olga Dmitryievna Karasyova (Kharlova-),F,19.0,164.0,55.0,Soviet Union,URS,1968 Summer,1968,Summer,Mexico City,Gymnastics,Gymnastics Women's Floor Exercise,NaN
113493,57497,Olga Dmitryievna Karasyova (Kharlova-),F,19.0,164.0,55.0,Soviet Union,URS,1968 Summer,1968,Summer,Mexico City,Gymnastics,Gymnastics Women's Horse Vault,NaN
113494,57497,Olga Dmitryievna Karasyova (Kharlova-),F,19.0,164.0,55.0,Soviet Union,URS,1968 Summer,1968,Summer,Mexico City,Gymnastics,Gymnastics Women's Uneven Bars,NaN
113495,57497,Olga Dmitryievna Karasyova (Kharlova-),F,19.0,164.0,55.0,Soviet Union,URS,1968 Summer,1968,Summer,Mexico City,Gymnastics,Gymnastics Women's Balance Beam,NaN
139055,69857,Vitaly Dmitryevich Lilichenko,M,21.0,167.0,64.0,Kazakhstan,KAZ,1998 Winter,1998,Winter,Nagano,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
139056,69857,Vitaly Dmitryevich Lilichenko,M,21.0,167.0,64.0,Kazakhstan,KAZ,1998 Winter,1998,Winter,Nagano,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
139057,69857,Vitaly Dmitryevich Lilichenko,M,21.0,167.0,64.0,Kazakhstan,KAZ,1998 Winter,1998,Winter,Nagano,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
139058,69857,Vitaly Dmitryevich Lilichenko,M,21.0,167.0,64.0,Kazakhstan,KAZ,1998 Winter,1998,Winter,Nagano,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
144195,72367,Timofey Timofeyevich Lunev,M,26.0,NaN,NaN,Soviet Union,URS,1952 Summer,1952,Summer,Helsinki,Athletics,Athletics Men's 400 metres Hurdles,NaN
164743,82731,Timofey Pavlovich Mozgov,M,26.0,216.0,113.0,Russia,RUS,2012 Summer,2012,Summer,London,Basketball,Basketball Men's Basketball,Bronze
203669,102254,Grand Duke Dmitry Pavlovich Romanov,M,20.0,NaN,NaN,Russia,RUS,1912 Summer,1912,Summer,Stockholm,Equestrianism,"Equestrianism Men's Jumping, Individual",NaN
203670,102254,Grand Duke Dmitry Pavlovich Romanov,M,20.0,NaN,NaN,Russia,RUS,1912 Summer,1912,Summer,Stockholm,Equestrianism,"Equestrianism Men's Jumping, Team",NaN
222428,111740,Timofey Sergeyevich Skopin,M,20.0,183.0,78.0,Russia,RUS,2010 Winter,2010,Winter,Vancouver,Speed Skating,Speed Skating Men's 500 metres,NaN
222925,111966,Timofey Vitalyevich Slivets,M,25.0,184.0,79.0,Belarus,BLR,2010 Winter,2010,Winter,Vancouver,Freestyle Skiing,Freestyle Skiing Men's Aerials,NaN
222926,111966,Timofey Vitalyevich Slivets,M,29.0,184.0,79.0,Russia,RUS,2014 Winter,2014,Winter,Sochi,Freestyle Skiing,Freestyle Skiing Men's Aerials,NaN
243584,121992,Vasily Dmitryevich Trofimov,M,33.0,NaN,NaN,Soviet Union,URS,1952 Summer,1952,Summer,Helsinki,Football,Football Men's Football,NaN
245003,122688,Demyan Dmitryevich Turchin,M,19.0,190.0,90.0,Belarus,BLR,2004 Summer,2004,Summer,Athina,Canoeing,"Canoeing Men's Kayak Fours, 1,000 metres",NaN

In [38]:
df[df['City'].isin(["London","Los Angeles"]) & (df['Name'].str.startswith("Timofey "))]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
54601,28005,Timofey Aleksandrovich Deynichenko,M,25.0,186.0,98.0,Belarus,BLR,2012 Summer,2012,Summer,London,Wrestling,"Wrestling Men's Heavyweight, Greco-Roman",NaN
82263,41781,Timofey Dmitriyevich Gordeychik,M,26.0,171.0,63.0,Belarus,BLR,2012 Summer,2012,Summer,London,Diving,Diving Men's Platform,NaN
164743,82731,Timofey Pavlovich Mozgov,M,26.0,216.0,113.0,Russia,RUS,2012 Summer,2012,Summer,London,Basketball,Basketball Men's Basketball,Bronze

In [41]:
df.query('City == "Amsterdam" and Age > 20')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
133,47,Erling Rudolf Aastad,M,30.0,177.0,74.0,Norway,NOR,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Long Jump,NaN
273,142,"David ""Dave"" Abbott",M,26.0,183.0,75.0,United States,USA,1928 Summer,1928,Summer,Amsterdam,Athletics,"Athletics Men's 5,000 metres",NaN
459,255,Mahmoud Ahmed Abdin,M,21.0,NaN,NaN,Egypt,EGY,1928 Summer,1928,Summer,Amsterdam,Fencing,"Fencing Men's Foil, Individual",NaN
460,255,Mahmoud Ahmed Abdin,M,21.0,NaN,NaN,Egypt,EGY,1928 Summer,1928,Summer,Amsterdam,Fencing,"Fencing Men's Foil, Team",NaN
664,385,"Max ""Xam"" Abegglen",M,26.0,NaN,NaN,Switzerland,SUI,1928 Summer,1928,Summer,Amsterdam,Football,Football Men's Football,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270572,135323,"Franois ""Frnz"" Zuang",M,33.0,NaN,NaN,Luxembourg,LUX,1928 Summer,1928,Summer,Amsterdam,Gymnastics,Gymnastics Men's Rings,NaN
270573,135323,"Franois ""Frnz"" Zuang",M,33.0,NaN,NaN,Luxembourg,LUX,1928 Summer,1928,Summer,Amsterdam,Gymnastics,Gymnastics Men's Pommelled Horse,NaN
270595,135336,Feliks Grzegorz uber,M,22.0,167.0,60.0,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's 400 metres,NaN
270962,135499,Alberts Zvejnieks,M,25.0,NaN,NaN,Latvia,LAT,1928 Summer,1928,Summer,Amsterdam,Wrestling,"Wrestling Men's Heavyweight, Greco-Roman",NaN
271100,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,NaN

In [42]:
df['Age'].between(20,30)

0          True
1          True
2          True
3         False
4          True
          ...
271111     True
271112     True
271113     True
271114     True
271115    False
Name: Age, Length: 271116, dtype: bool

In [ ]:
df['Age'] = 24  #update the value of age to 24

In [44]:
import numpy as np
a = df['New'] = np.where(df['Age'] > 20, 'Yes', 'No')

In [48]:
df1= df.drop(columns=['Age']) #inplace = true it will clear the column in original dataset

In [49]:
df1

,ID,Name,Sex,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New
0,1,A Dijiang,M,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,Yes
1,2,A Lamusi,M,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,Yes
2,3,Gunnar Nielsen Aaby,M,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes
3,4,Edgar Lindenau Aabye,M,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes
4,5,Christine Jacoba Aaftink,F,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Yes
271112,135570,Piotr ya,M,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Yes
271113,135570,Piotr ya,M,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Yes
271114,135571,Tomasz Ireneusz ya,M,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Yes
271115,135571,Tomasz Ireneusz ya,M,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Yes

In [50]:
df1['Age']=22

In [51]:
df1

,ID,Name,Sex,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Age
0,1,A Dijiang,M,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,Yes,22
1,2,A Lamusi,M,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,Yes,22
2,3,Gunnar Nielsen Aaby,M,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes,22
3,4,Edgar Lindenau Aabye,M,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,22
4,5,Christine Jacoba Aaftink,F,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Yes,22
271112,135570,Piotr ya,M,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Yes,22
271113,135570,Piotr ya,M,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Yes,22
271114,135571,Tomasz Ireneusz ya,M,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,22
271115,135571,Tomasz Ireneusz ya,M,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,22

In [52]:
df['Flag']=df['Age'].apply(lambda x: 1 if x>20 else 0)

In [53]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Flag
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,Yes,1
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,Yes,1
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes,1
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,1
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Yes,1
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Yes,1
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Yes,1
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,1
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,1

In [59]:
def categorize(row):
  if row['Weight'] < 60:
    return 'underweight'
  elif row['Weight'] >= 60 and row['Weight'] < 80:
    return 'normal'
  else:
    return 'overweight'

In [60]:
df1['category'] = df.apply(categorize, axis=1)

In [61]:
df1

,ID,Name,Sex,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Age,category
0,1,A Dijiang,M,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,Yes,22,overweight
1,2,A Lamusi,M,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,Yes,22,normal
2,3,Gunnar Nielsen Aaby,M,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes,22,overweight
3,4,Edgar Lindenau Aabye,M,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,22,overweight
4,5,Christine Jacoba Aaftink,F,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,22,overweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Yes,22,overweight
271112,135570,Piotr ya,M,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Yes,22,underweight
271113,135570,Piotr ya,M,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Yes,22,underweight
271114,135571,Tomasz Ireneusz ya,M,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,22,overweight
271115,135571,Tomasz Ireneusz ya,M,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,22,overweight

In [63]:
df2= pd.read_csv('/content/noc_regions.csv')

In [65]:
df2.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [66]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Flag
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,Yes,1
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,Yes,1
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes,1
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,1
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1

In [79]:
df.loc[[0,1],'Year'] = np.nan

In [80]:
df.head(25)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Flag,year
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,NaN,Summer,NaN,Basketball,Basketball Men's Basketball,NaN,Yes,1,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,NaN,Summer,NaN,Judo,Judo Men's Extra-Lightweight,NaN,Yes,1,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920.0,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes,1,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900.0,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,1,NaN
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988.0,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988.0,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN,Yes,1,NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992.0,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992.0,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN,Yes,1,NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994.0,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994.0,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN,Yes,1,NaN
10,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992.0,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN,Yes,1,NaN
11,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992.0,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN,Yes,1,NaN
12,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992.0,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN,Yes,1,NaN
13,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992.0,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN,Yes,1,NaN
14,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994.0,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN,Yes,1,NaN
15,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994.0,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN,Yes,1,NaN
16,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994.0,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN,Yes,1,NaN
17,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994.0,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN,Yes,1,NaN
18,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992.0,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN,Yes,1,NaN
19,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992.0,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN,Yes,1,NaN
20,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992.0,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN,Yes,1,NaN
21,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992.0,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN,Yes,1,NaN
22,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994.0,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN,Yes,1,NaN
23,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994.0,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN,Yes,1,NaN
24,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994.0,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN,Yes,1,NaN

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 18 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271114 non-null  float64
 10  Season  271116 non-null  object
 11  City    271114 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
 15  New     271116 non-null  object
 16  Flag    271116 non-null  int64
 17  year    0 non-null       float64
dtypes: float64(5), int64(2), object(11)
memory usage: 37.2+ MB

In [82]:
df.isna().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           2
Season         0
City           2
Sport          0
Event          0
Medal     231333
New            0
Flag           0
year      271116
dtype: int64

In [88]:
df.fillna(round(df['Year'].mean()))

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Flag,year
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1978.0,Summer,1978,Basketball,Basketball Men's Basketball,1978,Yes,1,1978.0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,1978.0,Summer,1978,Judo,Judo Men's Extra-Lightweight,1978,Yes,1,1978.0
2,3,Gunnar Nielsen Aaby,M,24.0,1978.0,1978.0,Denmark,DEN,1920 Summer,1920.0,Summer,Antwerpen,Football,Football Men's Football,1978,Yes,1,1978.0
3,4,Edgar Lindenau Aabye,M,34.0,1978.0,1978.0,Denmark/Sweden,DEN,1900 Summer,1900.0,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,1,1978.0
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988.0,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,1978,Yes,1,1978.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976.0,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,1978,Yes,1,1978.0
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014.0,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",1978,Yes,1,1978.0
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014.0,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",1978,Yes,1,1978.0
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998.0,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,1978,Yes,1,1978.0
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002.0,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,1978,Yes,1,1978.0

In [89]:
df[df['Year'].notna()]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Flag,year
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920.0,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes,1,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900.0,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,1,NaN
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988.0,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988.0,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN,Yes,1,NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992.0,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976.0,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Yes,1,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014.0,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Yes,1,NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014.0,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Yes,1,NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998.0,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,1,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002.0,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,1,NaN

In [95]:
df.drop(["year"],axis=1)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Flag
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,NaN,Summer,NaN,Basketball,Basketball Men's Basketball,NaN,Yes,1
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,NaN,Summer,NaN,Judo,Judo Men's Extra-Lightweight,NaN,Yes,1
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920.0,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes,1
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900.0,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,1
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988.0,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976.0,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Yes,1
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014.0,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Yes,1
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014.0,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Yes,1
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998.0,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,1
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002.0,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,1

In [96]:
df['City'].value_counts()

City
London                    22425
Athina                    15556
Sydney                    13821
Atlanta                   13780
Rio de Janeiro            13688
Beijing                   13602
Barcelona                 12976
Los Angeles               12423
Seoul                     12037
Munich                    10304
Montreal                   8641
Mexico City                8588
Helsinki                   8270
Roma                       8119
Tokyo                      7702
Moskva                     7191
Paris                      7169
Berlin                     6506
Amsterdam                  4992
Sochi                      4891
Melbourne                  4829
Vancouver                  4402
Torino                     4382
Stockholm                  4338
Antwerpen                  4292
Salt Lake City             4109
Innsbruck                  3639
Nagano                     3605
Albertville                3436
Lillehammer                3160
Calgary                    2639
Sarajevo                   2134
Lake Placid                2098
Grenoble                   1891
Sankt Moritz               1657
Sapporo                    1655
Cortina d'Ampezzo          1307
St. Louis                  1301
Squaw Valley               1116
Oslo                       1088
Garmisch-Partenkirchen      895
Chamonix                    460
Name: count, dtype: int64

In [97]:
df[df['City']=='London']['Sport'].value_counts()

Sport
Athletics                4107
Gymnastics               2257
Swimming                 2086
Shooting                 1220
Cycling                  1218
Fencing                  1093
Rowing                    955
Football                  757
Wrestling                 701
Hockey                    642
Sailing                   629
Basketball                574
Canoeing                  557
Equestrianism             557
Boxing                    530
Art Competitions          471
Water Polo                441
Judo                      383
Weightlifting             372
Tennis                    370
Handball                  347
Diving                    312
Volleyball                287
Archery                   277
Table Tennis              236
Badminton                 182
Taekwondo                 128
Modern Pentathlon         117
Synchronized Swimming     117
Triathlon                 110
Beach Volleyball           96
Rhythmic Gymnastics        95
Tug-Of-War                 40
Trampolining               32
Rugby                      30
Lacrosse                   24
Figure Skating             23
Motorboating               17
Racquets                   12
Polo                       12
Jeu De Paume               11
Name: count, dtype: int64

In [98]:
df.groupby('City')['Sport'].value_counts()

City         Sport
Albertville  Alpine Skiing           750
             Cross Country Skiing    717
             Biathlon                457
             Speed Skating           354
             Ice Hockey              267
                                    ...
Vancouver    Figure Skating          146
             Nordic Combined         131
             Luge                    107
             Curling                  93
             Skeleton                 47
Name: count, Length: 794, dtype: int64

In [ ]:
pivot = df.pivot(columns='City', index= 'ID', values='Sport')

In [109]:
group = df.groupby(['City', 'Sport'])['Name'].value_counts()

In [111]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,New,Flag,year
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,NaN,Summer,NaN,Basketball,Basketball Men's Basketball,NaN,Yes,1,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,NaN,Summer,NaN,Judo,Judo Men's Extra-Lightweight,NaN,Yes,1,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920.0,Summer,Antwerpen,Football,Football Men's Football,NaN,Yes,1,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900.0,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Yes,1,NaN
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988.0,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Yes,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976.0,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Yes,1,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014.0,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Yes,1,NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014.0,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Yes,1,NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998.0,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,1,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002.0,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Yes,1,NaN